/**
 * Generates `public/theme.css` from a bundled `@marianmeres/design-tokens`
 * theme, through the Bootstrap Reboot bridge.
 *
 * The output sets two things at once:
 *
 *   · `--app-color-*`  — the design tokens `public/app.css` consumes
 *   · `--bs-*`         — the variables `public/reboot.css` consumes
 *
 * Light lands on `:root`, dark on `:root.dark`, so switching modes is one class
 * on `<html>` and no stylesheet swapping.
 *
 * Run: `deno task example:theme` (the committed output is already current).
 *
 * @module
 */

import { generateThemedCss } from "@marianmeres/design-tokens/reboot";
import { getBundledTheme } from "@marianmeres/design-tokens/themes";

/** Any of the 50 bundled themes; `slateTealOcean` just reads well as a chat. */
const THEME = "slateTealOcean";
const PREFIX = "app-";

const schema = getBundledTheme(THEME);
if (!schema) throw new Error(`Unknown theme "${THEME}"`);

const css = `/*
 * @marianmeres/design-tokens "${THEME}" + Bootstrap Reboot bridge.
 * Generated by example/build-theme.ts — do not edit by hand.
 * Light on :root, dark on :root.dark; token prefix "${PREFIX}".
 */
` + generateThemedCss(schema, PREFIX, { prettierIgnore: true });

const out = new URL("./public/theme.css", import.meta.url);
await Deno.writeTextFile(out, css);

console.log(`Wrote ${out.pathname} (theme "${THEME}", prefix "${PREFIX}").`);
