/**
 * Generates the two stylesheets `public/index.html` does not hand-write.
 *
 * **`public/theme.css`** — one bundled `@marianmeres/design-tokens` theme,
 * emitted through the Bootstrap Reboot bridge with the **`vui-` prefix**, so it
 * sets two vocabularies at once:
 *
 *   · `--vui-color-*`  — the design tokens `vui-base.css` resolves (and, through
 *                        it, `public/app.css` reads as `--vui-surface` &c.)
 *   · `--bs-*`         — the variables `public/reboot.css` consumes
 *
 * Light lands on `:root`, dark on `:root.dark`, so switching modes is one class
 * on `<html>` and no stylesheet swapping.
 *
 * **`public/vui-base.css`** — a verbatim copy of `@marianmeres/vanilla-ui`'s
 * `components/base.css`, the kit's base style layer: the token vocabulary plus
 * the control primitives (`.vui-btn`, `.vui-input`, `.vui-badge`, `.vui-alert`,
 * …) this example's markup uses instead of hand-rolling its own. Copied rather
 * than linked so the demo runs offline; `<link id="vui-base">` in `index.html`
 * is the id the kit's own loader would skip, so a page that later pulls in a
 * vanilla-ui component reuses this one.
 *
 * The prefix is the whole integration: `vui-base.css` reads `--vui-color-*`, and
 * that is exactly what `generateThemedCss(schema, "vui-")` writes — the same
 * pairing vanilla-ui's own gallery uses.
 *
 * Run: `deno task example:styles` (the committed output is already current).
 *
 * @module
 */

import { generateThemedCss } from "@marianmeres/design-tokens/reboot";
import { getBundledTheme } from "@marianmeres/design-tokens/themes";

/** Any of the 50 bundled themes; `slateTealOcean` just reads well as a chat. */
const THEME = "slateTealOcean";

/** The kit's prefix. `vui-base.css` reads `--vui-color-*` and nothing else. */
const PREFIX = "vui-";

/* ------------------------------------------------------------------ theme */

const schema = getBundledTheme(THEME);
if (!schema) throw new Error(`Unknown theme "${THEME}"`);

const themeCss = `/*
 * @marianmeres/design-tokens "${THEME}" + Bootstrap Reboot bridge.
 * Generated by example/build-styles.ts — do not edit by hand.
 * Light on :root, dark on :root.dark; token prefix "${PREFIX}".
 */
` + generateThemedCss(schema, PREFIX, { prettierIgnore: true });

const themeOut = new URL("./public/theme.css", import.meta.url);
await Deno.writeTextFile(themeOut, themeCss);
console.log(`Wrote ${themeOut.pathname} (theme "${THEME}", prefix "${PREFIX}").`);

/* --------------------------------------------------------------- vui base */

// The kit publishes `components/` alongside `src/mod.ts`, and jsr.io serves
// those files raw (text/css, CORS on). Which version to copy is not a guess:
// deno.lock already says which one this repo resolves to.
const PKG = "@marianmeres/vanilla-ui";
const lock = JSON.parse(
	await Deno.readTextFile(new URL("../deno.lock", import.meta.url)),
) as { specifiers?: Record<string, string> };

const version = Object.entries(lock.specifiers ?? {})
	.find(([spec]) => spec.startsWith(`jsr:${PKG}@`))?.[1];
if (!version) throw new Error(`${PKG} is not in deno.lock — run \`deno install\`.`);

const kitUrl = `https://jsr.io/${PKG}/${version}/components/base.css`;
const res = await fetch(kitUrl);
if (!res.ok) throw new Error(`GET ${kitUrl} → ${res.status} ${res.statusText}`);
const baseCss = await res.text();

const baseOut = new URL("./public/vui-base.css", import.meta.url);
await Deno.writeTextFile(
	baseOut,
	`/*
 * @marianmeres/vanilla-ui ${version} — components/base.css, copied verbatim by
 * example/build-styles.ts. Do not edit by hand; edit the kit and re-run
 * \`deno task example:styles\`.
 */
` + baseCss,
);
console.log(`Wrote ${baseOut.pathname} (vanilla-ui ${version}).`);
